# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskId', models.CharField(max_length=100)),
                ('BarCode', models.CharField(max_length=10)),
                ('UserName', models.CharField(max_length=100)),
                ('Location', models.CharField(max_length=100)),
                ('Specialist', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BuildingName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cartridges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CartridgeName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrinterName', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='acts',
            name='Cartridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.Cartridges'),
        ),
        migrations.AddField(
            model_name='acts',
            name='IdBuilding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.Buildings'),
        ),
    ]
