# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0002_auto_20171022_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridges',
            name='Description',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
