# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0004_auto_20171022_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printers',
            name='Description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
