# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0006_auto_20171022_0125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acts',
            new_name='Act',
        ),
    ]
