# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-22 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0007_auto_20171022_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelCartridgePrinter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdCartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.Cartridge')),
                ('IdPrinter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.Printer')),
            ],
        ),
    ]
