# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0008_relcartridgeprinter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ShortDescription', models.CharField(max_length=100)),
                ('FullDescription', models.TextField()),
                ('CreateStamp', models.DateTimeField(auto_now_add=True)),
                ('LastEditionStamp', models.DateTimeField(auto_now=True)),
                ('Comment', models.TextField()),
            ],
        ),
    ]
