# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0009_userstories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='Approved',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userstories',
            name='Solved',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
