# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0010_auto_20171026_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstories',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userstories',
            name='Solved',
            field=models.BooleanField(default=False),
        ),
    ]
