# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0011_auto_20171026_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstories',
            name='Author',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
