# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0015_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserStories',
            new_name='UserStory',
        ),
    ]
