# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0016_auto_20171027_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='Printer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viz.Printer'),
            preserve_default=False,
        ),
    ]
