# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0018_auto_20171027_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='DeviceName',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='supply',
            old_name='CartridgeName',
            new_name='Name',
        ),
    ]
