# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0019_auto_20171027_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='act',
            name='Department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viz.Department'),
            preserve_default=False,
        ),
    ]
