# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0021_auto_20171028_2331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supply',
            old_name='Type',
            new_name='SupplyType',
        ),
    ]
