# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-28 20:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0023_auto_20171028_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='SupplyType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='viz.SupplyType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='act',
            name='Supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viz.Supply'),
        ),
    ]
