# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-10 15:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viz', '0024_auto_20171028_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='act',
            name='Group',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='act',
            name='Specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
